spring:
  profiles: default
  application:
    name: devops
  datasource:
    hikari:
      connectionTimeout: 2000
      maximumPoolSize: 5
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/books_catalog
    username: root
    password: '@Password1' 
  jpa:
    hibernate:
    ddl-auto: none
    jdbc:
      batch_size:5
    order_inserts: true
    show-sql: true
  jackson:
    serialization:
      write_dates_as_timestamps: false

